
export const POPULAR_TEAMS = [
    { id: 33, name: "Manchester United", logo: "https://media.api-sports.io/football/teams/33.png" },
    { id: 40, name: "Liverpool", logo: "https://media.api-sports.io/football/teams/40.png" },
    { id: 42, name: "Arsenal", logo: "https://media.api-sports.io/football/teams/42.png" },
    { id: 47, name: "Tottenham", logo: "https://media.api-sports.io/football/teams/47.png" },
    { id: 49, name: "Chelsea", logo: "https://media.api-sports.io/football/teams/49.png" },
    { id: 50, name: "Manchester City", logo: "https://media.api-sports.io/football/teams/50.png" },
    { id: 529, name: "Barcelona", logo: "https://media.api-sports.io/football/teams/529.png" },
    { id: 541, name: "Real Madrid", logo: "https://media.api-sports.io/football/teams/541.png" },
    { id: 530, name: "Atletico Madrid", logo: "https://media.api-sports.io/football/teams/530.png" },
    { id: 489, name: "AC Milan", logo: "https://media.api-sports.io/football/teams/489.png" },
    { id: 496, name: "Juventus", logo: "https://media.api-sports.io/football/teams/496.png" },
    { id: 497, name: "Inter", logo: "https://media.api-sports.io/football/teams/497.png" },
    { id: 157, name: "Bayern Munich", logo: "https://media.api-sports.io/football/teams/157.png" },
    { id: 165, name: "Borussia Dortmund", logo: "https://media.api-sports.io/football/teams/165.png" },
    { id: 85, name: "Paris Saint Germain", logo: "https://media.api-sports.io/football/teams/85.png" },
    { id: 1159, name: "Al Ahly SC", logo: "https://media.api-sports.io/football/teams/1159.png"},
    { id: 622, name: "Zamalek SC", logo: "https://media.api-sports.io/football/teams/622.png"},
    { id: 639, name: "Raja Casablanca", logo: "https://media.api-sports.io/football/teams/639.png"},
    { id: 641, name: "Wydad Casablanca", logo: "https://media.api-sports.io/football/teams/641.png"},
    { id: 634, name: "Esperance de Tunis", logo: "https://media.api-sports.io/football/teams/634.png"},
    { id: 603, name: "Al Hilal", logo: "https://media.api-sports.io/football/teams/603.png" },
    { id: 605, name: "Al Nassr", logo: "https://media.api-sports.io/football/teams/605.png" },
    { id: 1123, name: "Al Zawraa", logo: "https://media.api-sports.io/football/teams/1123.png" },
    { id: 1124, name: "Al Quwa Al Jawiya", logo: "https://media.api-sports.io/football/teams/1124.png" },
];

export const POPULAR_LEAGUES = [
    { id: 2, name: "UEFA Champions League", logo: "https://media.api-sports.io/football/leagues/2.png" },
    { id: 3, name: "UEFA Europa League", logo: "https://media.api-sports.io/football/leagues/3.png" },
    { id: 39, name: "Premier League", logo: "https://media.api-sports.io/football/leagues/39.png" },
    { id: 140, name: "La Liga", logo: "https://media.api-sports.io/football/leagues/140.png" },
    { id: 135, name: "Serie A", logo: "https://media.api-sports.io/football/leagues/135.png" },
    { id: 78, name: "Bundesliga", logo: "https://media.api-sports.io/football/leagues/78.png" },
    { id: 61, name: "Ligue 1", logo: "https://media.api-sports.io/football/leagues/61.png" },
    { id: 542, name: "Iraqi Premier League", logo: "https://media.api-sports.io/football/leagues/542.png" },
    { id: 307, name: "Saudi Professional League", logo: "https://media.api-sports.io/football/leagues/307.png" },
    { id: 203, name: "Egyptian Premier League", logo: "https://media.api-sports.io/football/leagues/203.png"},
    { id: 7, name: "CAF Champions League", logo: "https://media.api-sports.io/football/leagues/7.png"},
    { id: 1, name: "World Cup", logo: "https://media.api-sports.io/football/leagues/1.png" },
];
