
export const POPULAR_TEAMS = [
    // Europe (Top 5 Leagues + Portugal, Netherlands)
    { id: 33, name: "Manchester United", logo: "https://media.api-sports.io/football/teams/33.png", type: 'Club' },
    { id: 40, name: "Liverpool", logo: "https://media.api-sports.io/football/teams/40.png", type: 'Club' },
    { id: 42, name: "Arsenal", logo: "https://media.api-sports.io/football/teams/42.png", type: 'Club' },
    { id: 47, name: "Tottenham", logo: "https://media.api-sports.io/football/teams/47.png", type: 'Club' },
    { id: 49, name: "Chelsea", logo: "https://media.api-sports.io/football/teams/49.png", type: 'Club' },
    { id: 50, name: "Manchester City", logo: "https://media.api-sports.io/football/teams/50.png", type: 'Club' },
    { id: 529, name: "Barcelona", logo: "https://media.api-sports.io/football/teams/529.png", type: 'Club' },
    { id: 541, name: "Real Madrid", logo: "https://media.api-sports.io/football/teams/541.png", type: 'Club' },
    { id: 530, name: "Atletico Madrid", logo: "https://media.api-sports.io/football/teams/530.png", type: 'Club' },
    { id: 489, name: "AC Milan", logo: "https://media.api-sports.io/football/teams/489.png", type: 'Club' },
    { id: 496, name: "Juventus", logo: "https://media.api-sports.io/football/teams/496.png", type: 'Club' },
    { id: 497, name: "Inter", logo: "https://media.api-sports.io/football/teams/497.png", type: 'Club' },
    { id: 492, name: "Napoli", logo: "https://media.api-sports.io/football/teams/492.png", type: 'Club' },
    { id: 505, name: "AS Roma", logo: "https://media.api-sports.io/football/teams/505.png", type: 'Club' },
    { id: 157, name: "Bayern Munich", logo: "https://media.api-sports.io/football/teams/157.png", type: 'Club' },
    { id: 165, name: "Borussia Dortmund", logo: "https://media.api-sports.io/football/teams/165.png", type: 'Club' },
    { id: 168, name: "Bayer Leverkusen", logo: "https://media.api-sports.io/football/teams/168.png", type: 'Club' },
    { id: 173, name: "RB Leipzig", logo: "https://media.api-sports.io/football/teams/173.png", type: 'Club' },
    { id: 85, name: "Paris Saint Germain", logo: "https://media.api-sports.io/football/teams/85.png", type: 'Club' },
    { id: 91, name: "Monaco", logo: "https://media.api-sports.io/football/teams/91.png", type: 'Club' },
    { id: 94, name: "Marseille", logo: "https://media.api-sports.io/football/teams/94.png", type: 'Club' },
    { id: 211, name: "Benfica", logo: "https://media.api-sports.io/football/teams/211.png", type: 'Club' },
    { id: 212, name: "FC Porto", logo: "https://media.api-sports.io/football/teams/212.png", type: 'Club' },
    { id: 228, name: "Sporting CP", logo: "https://media.api-sports.io/football/teams/228.png", type: 'Club' },
    { id: 194, name: "Ajax", logo: "https://media.api-sports.io/football/teams/194.png", type: 'Club' },
    { id: 197, name: "PSV Eindhoven", logo: "https://media.api-sports.io/football/teams/197.png", type: 'Club' },
    { id: 408, name: "Feyenoord", logo: "https://media.api-sports.io/football/teams/408.png", type: 'Club' },
    // Asia (Key Leagues)
    { id: 603, name: "Al Hilal", logo: "https://media.api-sports.io/football/teams/603.png", type: 'Club' },
    { id: 605, name: "Al Nassr", logo: "https://media.api-sports.io/football/teams/605.png", type: 'Club' },
    { id: 611, name: "Al Ittihad", logo: "https://media.api-sports.io/football/teams/611.png", type: 'Club' },
    { id: 601, name: "Al Ahli", logo: "https://media.api-sports.io/football/teams/601.png", type: 'Club' },
    { id: 2282, name: "Al Sadd", logo: "https://media.api-sports.io/football/teams/2282.png", type: 'Club' },
    { id: 2281, name: "Al Duhail", logo: "https://media.api-sports.io/football/teams/2281.png", type: 'Club' },
    { id: 2289, name: "Al Ain", logo: "https://media.api-sports.io/football/teams/2289.png", type: 'Club' },
    { id: 2291, name: "Shabab Al Ahli", logo: "https://media.api-sports.io/football/teams/2291.png", type: 'Club' },
    { id: 1123, name: "Al Zawraa", logo: "https://media.api-sports.io/football/teams/1123.png", type: 'Club' },
    { id: 1124, name: "Al Quwa Al Jawiya", logo: "https://media.api-sports.io/football/teams/1124.png", type: 'Club' },
    { id: 1125, name: "Al Shorta", logo: "https://media.api-sports.io/football/teams/1125.png", type: 'Club' },
    { id: 4238, name: "Al Karkh", logo: "https://media.api-sports.io/football/teams/4238.png", type: 'Club'},
    { id: 4239, name: "Naft Maysan", logo: "https://media.api-sports.io/football/teams/4239.png", type: 'Club'},
    { id: 4241, name: "Al Talaba", logo: "https://media.api-sports.io/football/teams/4241.png", type: 'Club'},
    // Africa (Key Leagues)
    { id: 1159, name: "Al Ahly SC", logo: "https://media.api-sports.io/football/teams/1159.png", type: 'Club'},
    { id: 622, name: "Zamalek SC", logo: "https://media.api-sports.io/football/teams/622.png", type: 'Club'},
    { id: 639, name: "Raja Casablanca", logo: "https://media.api-sports.io/football/teams/639.png", type: 'Club'},
    { id: 641, name: "Wydad Casablanca", logo: "https://media.api-sports.io/football/teams/641.png", type: 'Club'},
    { id: 634, name: "Esperance de Tunis", logo: "https://media.api-sports.io/football/teams/634.png", type: 'Club'},
    { id: 633, name: "Etoile du Sahel", logo: "https://media.api-sports.io/football/teams/633.png", type: 'Club'},
    { id: 1060, name: "Mamelodi Sundowns", logo: "https://media.api-sports.io/football/teams/1060.png", type: 'Club'},
    { id: 1063, name: "Orlando Pirates", logo: "https://media.api-sports.io/football/teams/1063.png", type: 'Club'},
    { id: 1062, name: "Kaizer Chiefs", logo: "https://media.api-sports.io/football/teams/1062.png", type: 'Club'},
    { id: 910, name: "TP Mazembe", logo: "https://media.api-sports.io/football/teams/910.png", type: 'Club'},
    // Americas (Key Leagues)
    { id: 126, name: "Flamengo", logo: "https://media.api-sports.io/football/teams/126.png", type: 'Club' },
    { id: 121, name: "Palmeiras", logo: "https://media.api-sports.io/football/teams/121.png", type: 'Club' },
    { id: 451, name: "Boca Juniors", logo: "https://media.api-sports.io/football/teams/451.png", type: 'Club' },
    { id: 436, name: "River Plate", logo: "https://media.api-sports.io/football/teams/436.png", type: 'Club' },
    { id: 1613, name: "Inter Miami", logo: "https://media.api-sports.io/football/teams/1613.png", type: 'Club' },
    { id: 1599, name: "LA Galaxy", logo: "https://media.api-sports.io/football/teams/1599.png", type: 'Club' },
    { id: 2223, name: "Club America", logo: "https://media.api-sports.io/football/teams/2223.png", type: 'Club' },
    { id: 2286, name: "Guadalajara", logo: "https://media.api-sports.io/football/teams/2286.png", type: 'Club' },
    // National Teams
    { id: 2, name: "France", logo: "https://media.api-sports.io/football/teams/2.png", type: 'National' },
    { id: 6, name: "Brazil", logo: "https://media.api-sports.io/football/teams/6.png", type: 'National' },
    { id: 8, name: "Germany", logo: "https://media.api-sports.io/football/teams/8.png", type: 'National' },
    { id: 9, name: "England", logo: "https://media.api-sports.io/football/teams/9.png", type: 'National' },
    { id: 10, name: "Portugal", logo: "https://media.api-sports.io/football/teams/10.png", type: 'National' },
    { id: 12, name: "Spain", logo: "https://media.api-sports.io/football/teams/12.png", type: 'National' },
    { id: 13, name: "Italy", logo: "https://media.api-sports.io/football/teams/13.png", type: 'National' },
    { id: 28, name: "Argentina", logo: "https://media.api-sports.io/football/teams/28.png", type: 'National' },
    { id: 27, name: "Netherlands", logo: "https://media.api-sports.io/football/teams/27.png", type: 'National' },
    { id: 21, name: "Belgium", logo: "https://media.api-sports.io/football/teams/21.png", type: 'National' },
    { id: 15, name: "Morocco", logo: "https://media.api-sports.io/football/teams/15.png", type: 'National' },
    { id: 19, name: "Egypt", logo: "https://media.api-sports.io/football/teams/19.png", type: 'National' },
    { id: 20, name: "Algeria", logo: "https://media.api-sports.io/football/teams/20.png", type: 'National' },
    { id: 29, name: "Tunisia", logo: "https://media.api-sports.io/football/teams/29.png", type: 'National' },
    { id: 769, name: "Iraq", logo: "https://media.api-sports.io/football/teams/769.png", type: 'National' },
    { id: 768, name: "Saudi Arabia", logo: "https://media.api-sports.io/football/teams/768.png", type: 'National' },
    { id: 775, name: "Qatar", logo: "https://media.api-sports.io/football/teams/775.png", type: 'National' },
    { id: 25, name: "Japan", logo: "https://media.api-sports.io/football/teams/25.png", type: 'National' },
    { id: 24, name: "South Korea", logo: "https://media.api-sports.io/football/teams/24.png", type: 'National' },
    // More European teams
    { id: 504, name: "Lazio", logo: "https://media.api-sports.io/football/teams/504.png", type: 'Club' },
    { id: 169, name: "Eintracht Frankfurt", logo: "https://media.api-sports.io/football/teams/169.png", type: 'Club' },
    { id: 79, name: "Lille", logo: "https://media.api-sports.io/football/teams/79.png", type: 'Club' },
    { id: 548, name: "Sevilla", logo: "https://media.api-sports.io/football/teams/548.png", type: 'Club' },
    { id: 536, name: "Real Sociedad", logo: "https://media.api-sports.io/football/teams/536.png", type: 'Club' },
    { id: 38, name: "Leicester", logo: "https://media.api-sports.io/football/teams/38.png", type: 'Club' },
    { id: 34, name: "Newcastle", logo: "https://media.api-sports.io/football/teams/34.png", type: 'Club' },
    { id: 66, name: "Aston Villa", logo: "https://media.api-sports.io/football/teams/66.png", type: 'Club' },
    { id: 221, name: "Celtic", logo: "https://media.api-sports.io/football/teams/221.png", type: 'Club' },
    { id: 247, name: "Rangers", logo: "https://media.api-sports.io/football/teams/247.png", type: 'Club' },
    { id: 585, name: "Galatasaray", logo: "https://media.api-sports.io/football/teams/585.png", type: 'Club' },
    { id: 645, name: "Fenerbahce", logo: "https://media.api-sports.io/football/teams/645.png", type: 'Club' },
];

export const POPULAR_LEAGUES = [
    { id: 2, name: "UEFA Champions League", logo: "https://media.api-sports.io/football/leagues/2.png" },
    { id: 3, name: "UEFA Europa League", logo: "https://media.api-sports.io/football/leagues/3.png" },
    { id: 848, name: "UEFA Conference League", logo: "https://media.api-sports.io/football/leagues/848.png"},
    { id: 1, name: "World Cup", logo: "https://media.api-sports.io/football/leagues/1.png" },
    { id: 4, name: "Euro Championship", logo: "https://media.api-sports.io/football/leagues/4.png" },
    { id: 9, name: "Copa America", logo: "https://media.api-sports.io/football/leagues/9.png" },
    { id: 6, name: "Africa Cup of Nations", logo: "https://media.api-sports.io/football/leagues/6.png" },
    { id: 884, name: "AFC Asian Cup", logo: "https://media.api-sports.io/football/leagues/884.png"},
    { id: 39, name: "Premier League", logo: "https://media.api-sports.io/football/leagues/39.png" },
    { id: 140, name: "La Liga", logo: "https://media.api-sports.io/football/leagues/140.png" },
    { id: 135, name: "Serie A", logo: "https://media.api-sports.io/football/leagues/135.png" },
    { id: 78, name: "Bundesliga", logo: "https://media.api-sports.io/football/leagues/78.png" },
    { id: 61, name: "Ligue 1", logo: "https://media.api-sports.io/football/leagues/61.png" },
    { id: 307, name: "Saudi Professional League", logo: "https://media.api-sports.io/football/leagues/307.png" },
    { id: 542, name: "Iraq Stars League", logo: "https://media.api-sports.io/football/leagues/542.png" },
    { id: 310, name: "Qatar Stars League", logo: "https://media.api-sports.io/football/leagues/310.png"},
    { id: 304, name: "UAE Pro League", logo: "https://media.api-sports.io/football/leagues/304.png"},
    { id: 203, name: "Egyptian Premier League", logo: "https://media.api-sports.io/football/leagues/203.png"},
    { id: 200, name: "Moroccan Botola Pro", logo: "https://media.api-sports.io/football/leagues/200.png"},
    { id: 202, name: "Tunisian Ligue 1", logo: "https://media.api-sports.io/football/leagues/202.png"},
    { id: 199, name: "Algerian Ligue 1", logo: "https://media.api-sports.io/football/leagues/199.png"},
    { id: 7, name: "CAF Champions League", logo: "https://media.api-sports.io/football/leagues/7.png"},
    { id: 14, name: "AFC Champions League", logo: "https://media.api-sports.io/football/leagues/14.png"},
    { id: 11, name: "Copa Libertadores", logo: "https://media.api-sports.io/football/leagues/11.png"},
    { id: 253, name: "Major League Soccer", logo: "https://media.api-sports.io/football/leagues/253.png" },
    { id: 71, name: "Brasileirão Série A", logo: "https://media.api-sports.io/football/leagues/71.png" },
    { id: 128, name: "Argentine Primera División", logo: "https://media.api-sports.io/football/leagues/128.png"},
    { id: 88, name: "Eredivisie", logo: "https://media.api-sports.io/football/leagues/88.png" },
    { id: 94, name: "Primeira Liga", logo: "https://media.api-sports.io/football/leagues/94.png" },
    { id: 197, name: "Turkish Süper Lig", logo: "https://media.api-sports.io/football/leagues/197.png"},
    { id: 40, name: "Championship", logo: "https://media.api-sports.io/football/leagues/40.png" },
    { id: 143, name: "Copa del Rey", logo: "https://media.api-sports.io/football/leagues/143.png"},
    { id: 45, name: "FA Cup", logo: "https://media.api-sports.io/football/leagues/45.png"},
];
